
using DreamPoeBot.Loki.Game;
using System;
using System.Collections.Generic;
using static DreamPoeBot.Loki.Game.LokiPoe.InGameState;

namespace Lboto.Helpers
{
    public enum TaskPosition
    {
        Before,
        After,
        Replace
    }

    public enum TransitionType
    {
        Regular,
        Local,
        Vaal,
        Master,
        Trial,
        Incursion,
        Synthesis,
        Syndicate,
        Conqueror
    }

    public enum WithdrawResult
    {
        Success,
        Error,
        Unavailable,
    }
    public enum PauseTypeEnum
    {
        StashPauseProbability,
        TownMovePause,
        OtherPauseType // Добавь другие типы пауз, если они есть
    }
    public static class ScarabControlDict
    {
        internal static readonly Dictionary<string, Func<InventoryControlWrapper>> FragmentControlDict = new Dictionary<string, Func<InventoryControlWrapper>>
        {
            ["Sacrifice at Midnight"] = () => StashUi.FragmentTab.General.SacrificeatMidnight,
            ["Sacrifice at Dusk"] = () => StashUi.FragmentTab.General.SacrificeatDusk,
            ["Sacrifice at Dawn"] = () => StashUi.FragmentTab.General.SacrificeatDawn,
            ["Sacrifice at Noon"] = () => StashUi.FragmentTab.General.SacrificeatNoon,
            ["Abyss Scarab"] = () => StashUi.FragmentTab.Scarab.AbyssScarab,
            ["Abyss Scarab of Multitudes"] = () => StashUi.FragmentTab.Scarab.AbyssScarabofMultitudes,
            ["Abyss Scarab of Edifice"] = () => StashUi.FragmentTab.Scarab.AbyssScarabofEdifice,
            //["Abyss Scarab of Emptiness"] = () => StashUi.FragmentTab.Scarab.AbyssScarabofEmptiness,
            ["Ambush Scarab"] = () => StashUi.FragmentTab.Scarab.AmbushScarab,
            ["Ambush Scarab of Hidden Compartments"] = () => StashUi.FragmentTab.Scarab.AmbushScarabofHiddenCompartments,
            ["Ambush Scarab of Potency"] = () => StashUi.FragmentTab.Scarab.AmbushScarabofPotency,
            ["Ambush Scarab of Containment"] = () => StashUi.FragmentTab.Scarab.AmbushScarabofContainment,
            ["Ambush Scarab of Discernment"] = () => StashUi.FragmentTab.Scarab.AmbushScarabofDiscernment,
            ["Anarchy Scarab"] = () => StashUi.FragmentTab.Scarab.AnarchyScarab,
            ["Anarchy Scarab of Gigantification"] = () => StashUi.FragmentTab.Scarab.AnarchyScarabofGigantification,
            ["Anarchy Scarab of Partnership"] = () => StashUi.FragmentTab.Scarab.AnarchyScarabofPartnership,
            ["Bestiary Scarab"] = () => StashUi.FragmentTab.Scarab.BestiaryScarab,
            ["Bestiary Scarab of the Herd"] = () => StashUi.FragmentTab.Scarab.BestiaryScaraboftheHerd,
            ["Bestiary Scarab of Duplicating"] = () => StashUi.FragmentTab.Scarab.BestiaryScarabofDuplicating,
            //["Bestiary Scarab of the Shadowed Crow"] = () => StashUi.FragmentTab.Scarab.BestiaryScaraboftheShadowedCrow,
            ["Betrayal Scarab"] = () => StashUi.FragmentTab.Scarab.BetrayalScarab,
            //["Betrayal Scarab of Intelligence"] = () => StashUi.FragmentTab.Scarab.BetrayalScarabofIntelligence,
            ["Betrayal Scarab of Reinforcements"] = () => StashUi.FragmentTab.Scarab.BetrayalScarabofReinforcements,
            //["Betrayal Scarab of Perpetuation"] = () => StashUi.FragmentTab.Scarab.BetrayalScarabofPerpetuation,
            ["Beyond Scarab"] = () => StashUi.FragmentTab.Scarab.BeyondScarab,
            //["Beyond Scarab of Corruption"] = () => StashUi.FragmentTab.Scarab.BeyondScarabofCorruption,
            ["Beyond Scarab of Haemophilia"] = () => StashUi.FragmentTab.Scarab.BeyondScarabofHaemophilia,
            ["Beyond Scarab of Resurgence"] = () => StashUi.FragmentTab.Scarab.BeyondScarabofResurgence,
            ["Beyond Scarab of the Invasion"] = () => StashUi.FragmentTab.Scarab.BeyondScaraboftheInvasion,
            ["Blight Scarab"] = () => StashUi.FragmentTab.Scarab.BlightScarab,
            ["Blight Scarab of Blooming"] = () => StashUi.FragmentTab.Scarab.BlightScarabofBlooming,
            ["Blight Scarab of Invigoration"] = () => StashUi.FragmentTab.Scarab.BlightScarabofInvigoration,
            //["Blight Scarab of Bounty"] = () => StashUi.FragmentTab.Scarab.BlightScarabofBounty,
            //["Blight Scarab of Oils"] = () => StashUi.FragmentTab.Scarab.BlightScarabofOils,
            ["Blight Scarab of Blooming"] = () => StashUi.FragmentTab.Scarab.BlightScarabofBlooming,
            ["Breach Scarab"] = () => StashUi.FragmentTab.Scarab.BreachScarab,
            //["Breach Scarab of the Dreamer"] = () => StashUi.FragmentTab.Scarab.BreachScaraboftheDreamer,
            ["Breach Scarab of Lordship"] = () => StashUi.FragmentTab.Scarab.BreachScarabofLordship,
            ["Breach Scarab of Splintering"] = () => StashUi.FragmentTab.Scarab.BreachScarabofSplintering,
            ["Breach Scarab of Snares"] = () => StashUi.FragmentTab.Scarab.BreachScarabofSnares,
            //["Cartography Scarab"] = () => StashUi.FragmentTab.Scarab.CartographyScarab,
            //["Cartography Scarab of Ascension"] = () => StashUi.FragmentTab.Scarab.CartographyScarabofAscension,
           // ["Cartography Scarab of Singularity"] = () => StashUi.FragmentTab.Scarab.CartographyScarabofSingularity,
            ["Cartography Scarab of Corruption"] = () => StashUi.FragmentTab.Scarab.CartographyScarabofCorruption,
            ["Cartography Scarab of Risk"] = () => StashUi.FragmentTab.Scarab.CartographyScarabofRisk,
            ["Cartography Scarab of Escalation"] = () => StashUi.FragmentTab.Scarab.CartographyScarabofEscalation,
            ["Cartography Scarab of the Multitude"] = () => StashUi.FragmentTab.Scarab.CartographyScaraboftheMultitude,
            //["Cartography Scarab of Duplication"] = () => StashUi.FragmentTab.Scarab.CartographyScarabofDuplication,
            ["Delirium Scarab"] = () => StashUi.FragmentTab.Scarab.DeliriumScarab,
            ["Delirium Scarab of Mania"] = () => StashUi.FragmentTab.Scarab.DeliriumScarabofMania,
            ["Delirium Scarab of Paranoia"] = () => StashUi.FragmentTab.Scarab.DeliriumScarabofParanoia,
            ["Delirium Scarab of Neuroses"] = () => StashUi.FragmentTab.Scarab.DeliriumScarabofNeuroses,
            ["Delirium Scarab of Delusions"] = () => StashUi.FragmentTab.Scarab.DeliriumScarabofDelusions,
            //["Divination Scarab"] = () => StashUi.FragmentTab.Scarab.DivinationScarab,
           // ["Divination Scarab of Curation"] = () => StashUi.FragmentTab.Scarab.DivinationScarabofCuration,
            //["Divination Scarab of Completion"] = () => StashUi.FragmentTab.Scarab.DivinationScarabofCompletion,
            ["Domination Scarab"] = () => StashUi.FragmentTab.Scarab.DominationScarab,
            //["Domination Scarab of Abnormality"] = () => StashUi.FragmentTab.Scarab.DominationScarabofAbnormality,
            //["Domination Scarab of Teachings"] = () => StashUi.FragmentTab.Scarab.DominationScarabofTeachings,
            ["Domination Scarab of Terrors"] = () => StashUi.FragmentTab.Scarab.DominationScarabofTerrors,
            ["Essence Scarab"] = () => StashUi.FragmentTab.Scarab.EssenceScarab,
            ["Essence Scarab of Ascent"] = () => StashUi.FragmentTab.Scarab.EssenceScarabofAscent,
            ["Essence Scarab of Stability"] = () => StashUi.FragmentTab.Scarab.EssenceScarabofStability,
            ["Essence Scarab of Calcification"] = () => StashUi.FragmentTab.Scarab.EssenceScarabofCalcification,
            ["Expedition Scarab"] = () => StashUi.FragmentTab.Scarab.ExpeditionScarab,
            ["Expedition Scarab of Runefinding"] = () => StashUi.FragmentTab.Scarab.ExpeditionScarabofRunefinding,
            ["Expedition Scarab of Verisium Powder"] = () => StashUi.FragmentTab.Scarab.ExpeditionScarabofVerisiumPowder,
            //["Expedition Scarab of the Skald"] = () => StashUi.FragmentTab.Scarab.ExpeditionScaraboftheSkald,
            ["Expedition Scarab of Archaeology"] = () => StashUi.FragmentTab.Scarab.ExpeditionScarabofArchaeology,
            ["Harbinger Scarab"] = () => StashUi.FragmentTab.Scarab.HarbingerScarab,
            //["Harbinger Scarab of Discernment"] = () => StashUi.FragmentTab.Scarab.HarbingerScarabofDiscernment,
            ["Harbinger Scarab of Regency"] = () => StashUi.FragmentTab.Scarab.HarbingerScarabofRegency,
            ["Harbinger Scarab of Warhoards"] = () => StashUi.FragmentTab.Scarab.HarbingerScarabofWarhoards,
            ["Harvest Scarab"] = () => StashUi.FragmentTab.Scarab.HarvestScarab,
            ["Harvest Scarab of Doubling"] = () => StashUi.FragmentTab.Scarab.HarvestScarabofDoubling,
            ["Harvest Scarab of Cornucopia"] = () => StashUi.FragmentTab.Scarab.HarvestScarabofCornucopia,
            ["Incursion Scarab"] = () => StashUi.FragmentTab.Scarab.IncursionScarab,
            ["Incursion Scarab of Invasion"] = () => StashUi.FragmentTab.Scarab.IncursionScarabofInvasion,
            ["Incursion Scarab of Champions"] = () => StashUi.FragmentTab.Scarab.IncursionScarabofChampions,
            ["Incursion Scarab of Timelines"] = () => StashUi.FragmentTab.Scarab.IncursionScarabofTimelines,
            ["Influencing Scarab of the Shaper"] = () => StashUi.FragmentTab.Scarab.InfluencingScaraboftheShaper,
            ["Influencing Scarab of the Elder"] = () => StashUi.FragmentTab.Scarab.InfluencingScaraboftheElder,
            ["Influencing Scarab of Hordes"] = () => StashUi.FragmentTab.Scarab.InfluencingScarabofHordes,
            ["Influencing Scarab of Conversion"] = () => StashUi.FragmentTab.Scarab.InfluencingScarabofConversion,
            ["Legion Scarab"] = () => StashUi.FragmentTab.Scarab.LegionScarab,
            ["Legion Scarab of Officers"] = () => StashUi.FragmentTab.Scarab.LegionScarabofOfficers,
            ["Legion Scarab of Command"] = () => StashUi.FragmentTab.Scarab.LegionScarabofCommand,
            //["Legion Scarab of The Sekhema"] = () => StashUi.FragmentTab.Scarab.LegionScarabofTheSekhema,
            ["Legion Scarab of Eternal Conflict"] = () => StashUi.FragmentTab.Scarab.LegionScarabofEternalConflict,
            //["Reliquary Scarab"] = () => StashUi.FragmentTab.Scarab.ReliquaryScarab,
            //["Reliquary Scarab of Overlords"] = () => StashUi.FragmentTab.Scarab.ReliquaryScarabofOverlords,
            //["Reliquary Scarab of Vision"] = () => StashUi.FragmentTab.Scarab.ReliquaryScarabofVision,
            ["Ritual Scarab of Selectiveness"] = () => StashUi.FragmentTab.Scarab.RitualScarabofSelectiveness,
            //["Ritual Scarab of Recognition"] = () => StashUi.FragmentTab.Scarab.RitualScarabofRecognition,
            ["Ritual Scarab of Abundance"] = () => StashUi.FragmentTab.Scarab.RitualScarabofAbundance,
            ["Sulphite Scarab"] = () => StashUi.FragmentTab.Scarab.SulphiteScarab,
            //["Sulphite Scarab of Greed"] = () => StashUi.FragmentTab.Scarab.SulphiteScarabofGreed,
            ["Sulphite Scarab of Fumes"] = () => StashUi.FragmentTab.Scarab.SulphiteScarabofFumes,
            ["Torment Scarab"] = () => StashUi.FragmentTab.Scarab.TormentScarab,
            ["Torment Scarab of Peculiarity"] = () => StashUi.FragmentTab.Scarab.TormentScarabofPeculiarity,
            //["Torment Scarab of Release"] = () => StashUi.FragmentTab.Scarab.TormentScarabofRelease,
            ["Ultimatum Scarab"] = () => StashUi.FragmentTab.Scarab.UltimatumScarab,
            ["Ultimatum Scarab of Bribing"] = () => StashUi.FragmentTab.Scarab.UltimatumScarabofBribing,
            ["Ultimatum Scarab of Dueling"] = () => StashUi.FragmentTab.Scarab.UltimatumScarabofDueling,
            ["Ultimatum Scarab of Catalysing"] = () => StashUi.FragmentTab.Scarab.UltimatumScarabofCatalysing,
            ["Ultimatum Scarab of Inscription"] = () => StashUi.FragmentTab.Scarab.UltimatumScarabofInscription,
            ["Horned Scarab of Bloodlines"] = () => StashUi.FragmentTab.Scarab.HornedScarabofBloodlines,
            ["Horned Scarab of Nemeses"] = () => StashUi.FragmentTab.Scarab.HornedScarabofNemeses,
            ["Horned Scarab of Tradition"] = () => StashUi.FragmentTab.Scarab.HornedScarabofTradition,
            ["Horned Scarab of Pandemonium"] = () => StashUi.FragmentTab.Scarab.HornedScarabofPandemonium,
            ["Horned Scarab of Awakening"] = () => StashUi.FragmentTab.Scarab.HornedScarabofAwakening,
            ["Horned Scarab of Preservation"] = () => StashUi.FragmentTab.Scarab.HornedScarabofPreservation,
            ["Horned Scarab of Glittering"] = () => StashUi.FragmentTab.Scarab.HornedScarabofGlittering,
            //["Mysterious Scarab"] = () => StashUi.FragmentTab.Scarab.MysteriousScarab,
            ["Scarab of Monstrous Lineage"] = () => StashUi.FragmentTab.Scarab.ScarabofMonstrousLineage,
            ["Scarab of Adversaries"] = () => StashUi.FragmentTab.Scarab.ScarabofAdversaries,
            ["Scarab of Hunted Traitors"] = () => StashUi.FragmentTab.Scarab.ScarabofHuntedTraitors,
            ["Scarab of Stability Scarab"] = () => StashUi.FragmentTab.Scarab.ScarabofStability,
            ["Offering to the Goddess"] = () => StashUi.FragmentTab.General.OfferingtotheGoddess,
        };
    }
}
